import React, { useState } from "react";
import {
  View,
  Text,
  TextInput,
  FlatList,
  TouchableOpacity,
  StyleSheet,
} from "react-native";
import Ionicons from "react-native-vector-icons/Ionicons";
import AntDesign from "react-native-vector-icons/AntDesign";

const cities = [
  "New York",
  "Los Angeles",
  "Chicago",
  "Houston",
  "Phoenix",
  "Philadelphia",
  "San Antonio",
  "San Diego",
  "Dallas",
  "San Jose",
  "Lucknow",
  "Mumbai",
  "Delhi",
  "Bangalore",
  "Hyderabad",
  "Ahmedabad",
  "Chennai",
  "Kolkata",
  "Surat",
  "Pune",
  "Jaipur",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan-Dombivli",
  "Vasai-Virar",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Howrah",
  "Ranchi",
  "Gwalior",
  "Jabalpur",
  "Coimbatore",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubli-Dharwad",
  "Mysore",
  "Tiruchirappalli",
  "Bareilly",
  "Aligarh",
  "Tiruppur",
  "Moradabad",
  "Jalandhar",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Guntur",
  "Bhiwandi",
  "Saharanpur",
  "Gorakhpur",
  "Bikaner",
  "Amravati",
  "Noida",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Nellore",
  "Bhavnagar",
  "Dehradun",
  "Durgapur",
  "Asansol",
  "Rourkela",
  "Nanded",
  "Kolhapur",
  "Ajmer",
  "Akola",
  "Gulbarga",
  "Jamnagar",
  "Ujjain",
  "Loni",
  "Siliguri",
  "Jhansi",
  "Ulhasnagar",
  "Jammu",
  "Sangli-Miraj & Kupwad",
  "Mangalore",
  "Erode",
  "Belgaum",
  "Ambattur",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Udaipur",
  "Maheshtala",
  "Davanagere",
  "Kozhikode",
  "Kurnool",
  "Rajpur Sonarpur",
  "Bokaro Steel City",
  "South Dumdum",
  "Bellary",
  "Patiala",
  "Gopalpur",
  "Agartala",
  "Bhagalpur",
  "Muzaffarnagar",
  "Bhatpara",
  "Panihati",
  "Latur",
  "Dhule",
  "Rohtak",
  "Korba",
  "Bhilwara",
  "Berhampur",
  "Muzaffarpur",
  "Ahmednagar",
  "Mathura",
  "Kollam",
  "Avadi",
  "Kadapa",
  "Kamarhati",
  "Sambalpur",
  "Bilaspur",
  "Shahjahanpur",
  "Satara",
  "Bijapur",
  "Rampur",
  "Shimoga",
  "Chandrapur",
  "Junagadh",
  "Thrissur",
  "Alwar",
  "Bardhaman",
  "Kulti",
  "Kakinada",
  "Nizamabad",
  "Parbhani",
  "Tumkur",
  "Hisar",
  "Ozhukarai",
  "Bihar Sharif",
  "Panipat",
  "Darbhanga",
  "Bally",
  "Aizawl",
  "Dewas",
  "Ichalkaranji",
  "Tirupati",
  "Karnal",
  "Bathinda",
  "Jalna",
  "Barasat",
  "Kirari Suleman Nagar",
  "Purnia",
  "Satna",
  "Mau",
  "Sonipat",
  "Farrukhabad",
  "Sagar",
  "Rourkela Industrial Township",
  "Durg",
  "Imphal",
  "Ratlam",
  "Hapur",
  "Arrah",
  "Karimnagar",
  "Anantapur",
  "Etawah",
  "Ambarnath",
  "North Dumdum",
  "Bharatpur",
  "Begusarai",
  "New Delhi",
  "Gandhidham",
  "Baranagar",
  "Tiruvottiyur",
  "Pondicherry",
  "Sikar",
  "Thoothukudi",
  "Rewa",
  "Mirzapur",
  "Raichur",
  "Pali",
  "Ramagundam",
  "Silchar",
  "Haridwar",
  "Vijayanagaram",
  "Tenali",
  "Nagercoil",
  "Sri Ganganagar",
  "Karawal Nagar",
  "Mango",
  "Thanjavur",
  "Bulandshahr",
  "Uluberia",
  "Katni",
  "Sambhal",
  "Singrauli",
  "Nadiad",
  "Secunderabad",
  "Naihati",
  "Yamunanagar",
  "Bidhannagar",
  "Pallavaram",
  "Bidar",
  "Munger",
  "Panchkula",
  "Burhanpur",
  "Raurkela",
  "Kharagpur",
  "Dindigul",
  "Gandhinagar",
  "Hospet",
  "Nangloi Jat",
  "Malda",
  "Ongole",
  "Deoghar",
  "Chapra",
  "Haldia",
  "Khandwa",
  "Nandyal",
  "Morena",
  "Amroha",
  "Anand",
  "Bhind",
  "Bhalswa Jahangir Pur",
  "Madhyamgram",
  "Bhiwani",
  "Berhampore",
  "Ambala",
  "Morbi",
  "Fatehpur",
  "Raebareli",
  "Khora",
  "Chittoor",
  "Bhusawal",
  "Orai",
  "Bahraich",
  "Phagwara",
  "Buxar",
  "Jehanabad",
  "Aurangabad",
  "Gangapur City",
  "Khammam",
  "Madhubani",
  "Thoothukkudi",
  "Patan",
  "Tonk",
  "Karaikudi",
  "Pudukkottai",
  "Tinsukia",
  "Itarsi",
  "Kohima",
  "Rayachoti",
  "Sopore",
  "Sikar",
  "Port Blair",
  "Shillong",
  "Saharsa",
  "Tiruchengode",
  "Gangtok",
  "Suryapet",
  "Mahbubnagar",
  "Sambhal",
  "Sunabeda",
  "Mehsana",
  "Thalassery",
  "Kumbakonam",
  "Adoni",
  "Udupi",
  "Tenali",
  "Proddatur",
  "Nagda",
  "Sirsa",
  "Nawada",
  "Sircilla",
  "Barnala",
  "Mokameh",
  "Jagdalpur",
  "Tadpatri",
  "Srikakulam",
  "Begusarai",
  "Bhadravati",
  "Guntakal",
  "Sirhind Fatehgarh Sahib",
  "Jorhat",
  "Pulgaon",
  "Medininagar",
  "Hindupur",
  "Kumbakonam",
  "Tadepalligudem",
  "Gudur",
  "Palwancha",
  "Kavali",
  "Mancherial",
  "Bhiwadi",
  "Baramati",
  "Mandya",
  "Bhadravati",
  "Kanhangad",
  "Bettiah",
  "Bhimavaram",
  "Madanapalle",
  "Suryapet",
  "Srikalahasti",
  "Narasaraopet",
  "Chhapra",
  "Mahbubnagar",
  "Hosur",
  "Bhiwandi",
  "Theni Allinagaram",
  "Puttur",
  "Gudivada",
  "Dharmavaram",
  "Nagapattinam",
  "Miryalaguda",
  "Sasaram",
  "Srikakulam",
  "Tadpatri",
  "Bar",
];

export default function SearchBar({ cityHandler, setSuggestionsVisible }) {
  const [searchTerm, setSearchTerm] = useState();
  const [filteredCities, setFilteredCities] = useState([]);

  const handleSearch = (text) => {
    setSearchTerm(text);
    console.log("search item");
    if (text) {
      const filtered = cities
        .filter((city) => city.toLowerCase().includes(text.toLowerCase()))
        .slice(0, 5);
      setFilteredCities(filtered);
      setSuggestionsVisible(true);
    } else {
      setFilteredCities([]);
      setSuggestionsVisible(false);
    }
  };

  const handleCityPress = (city) => {
    console.log(city);
    setSearchTerm(city);
    setFilteredCities([]);
    setSuggestionsVisible(false);
    cityHandler(city);
    console.log(city);
  };

  return (
    <View style={{ marginTop: 15, flexDirection: "row" }}>
      <View style={styles.searchBarContainer}>
        <Ionicons name="location-sharp" size={24} style={styles.icon} />
        <TextInput
          style={styles.textInput}
          placeholder="Search"
          value={searchTerm}
          onChangeText={handleSearch}
        />
        {filteredCities.length > 0 && (
          <FlatList
            style={styles.suggestionsContainer}
            data={filteredCities}
            keyExtractor={(item) => item}
            renderItem={({ item }) => (
              <TouchableOpacity onPress={() => handleCityPress(item)}>
                <Text style={styles.suggestionText}>{item}</Text>
              </TouchableOpacity>
            )}
          />
        )}
        <TouchableOpacity
          style={styles.rightButton}
          onPress={() => handleCityPress(searchTerm)}
        >
          <AntDesign name="clockcircle" size={11} style={styles.clockIcon} />
          <Text>Search</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  searchBarContainer: {
    backgroundColor: "#eee",
    borderRadius: 50,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
    flex: 1,
    height: 50,
  },
  icon: {
    marginLeft: 10,
  },
  textInput: {
    backgroundColor: "#eee",
    borderRadius: 20,
    fontWeight: "700",
    marginTop: 7,
    marginLeft: 10,
    flex: 1,
  },
  rightButton: {
    backgroundColor: "white",
    marginRight: 20,
    flexDirection: "row",
    padding: 9,
    borderRadius: 30,
    alignItems: "center",
  },
  clockIcon: {
    marginRight: 6,
  },
  suggestionsContainer: {
    backgroundColor: "white",
    position: "absolute",
    flex: 1,
    top: 60,
    left: 0,
    right: 0,
    zIndex: 1,
  },
  suggestionText: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
});
